version: "2"
authtoken: 6HkyZNTecqKR5vvmZ4QU8_53fqex7WT6p4A32AsnYTu
tunnels:
  web-ui:
    addr: 3000
    proto: http
  backend:
    addr: 8000
    proto: http
  minio:
    addr: 9000
    proto: http
